name = "cf-workers-status-page"
compatibility_date = "2050-09-14"
account_id = ""
workers_dev = true
main = "./index.js"

[build]
command = "npm run build"
#account_id = ""
#type = "webpack"
#webpack_config = "node_modules/flareact/webpack"

#[triggers]
#crons = ["*/2 * * * *"]

[site]
bucket = "out"
#entry-point = "./"
